routes/web.php
<?php

use App\Http\Controllers\AdministrateurController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class,'index'])->name('home');
Route::get('/', [SessionController::class , 'obtenircode'])->name('obtenircode');
Route::post('/login', [SessionController::class , 'login'])->name('session.login');
Route::post('/generatecode', [SessionController::class , 'generatecode'])->name('session.generatecode');
Route::get('/showverifcode', [SessionController::class , 'showverifcode'])->name('session.showverifcode');
Route::post('/verifcode', [SessionController::class , 'verifcode'])->name('session.verifcode');
Route::get('/sms', [SessionController::class , 'sms'])->name('sms');

Route::get('/resultat', function () {
    $candidats = \App\Models\CandidatPresidentielle::all();
    return view('voting.resultat',compact('candidats'));
});

Route::group(['prefix'=>'admin','as'=>'admin.'], function () {
    Route::get('/',[AdministrateurController::class, 'index'])->name('index');
    Route::get('/import',[AdministrateurController::class, 'import'])->name('import');
    Route::post('/import_in',[AdministrateurController::class, 'import_in'])->name('import_in');
    Route::get('/user',[UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/edit',[UserController::class, 'edit'])->name('user.edit');
    Route::post('/user/update/{id}',[UserController::class, 'update'])->name('user.update');
    Route::get('/candidat/commissaire',[AdministrateurController::class,'resultatcommissaire'])->name('resultatcommissaire');
});

Route::group(['prefix'=>'vote','as'=>'vote.'], function () {
    Route::get('/',[VoteController::class, 'index'])->name('index');
    Route::get('/commisaire',[VoteController::class, 'commisaire'])->name('commisaire');
    Route::get('/voter/{id}',[VoteController::class, 'voter'])->name('voter');
    Route::get('/voter/commissaire/{id}',[VoteController::class, 'voterCommissaire'])->name('votecommissaire');
    Route::get('/voter/commissaire-adjoint/{id}',[VoteController::class, 'voterCommissaireAdjoint'])->name('votecommissaireadjoint');
    Route::get('/felicitaion',[VoteController::class, 'felicitaion'])->name('felicitaion');
    Route::get('/votrechoix',[VoteController::class, 'votrechoix'])->name('votrechoix');
    Route::post('/fullcommissaire',[VoteController::class, 'fullCommissaire'])->name('fullcommissaire');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'matricule',
        'nomprenom',
        'name',
        'genre',
        'fonction',
        'telephone',
        'email',
        'code_agence',
        'codegene',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // dd(request('filtreemail'));

        $users = User::when(request('nomprenom'), function ($q, $v) {
            $q->whereLike('nomprenom', $v);
        })->when(request('matricule'), function ($q, $v) {
            $q->whereLike('matricule', $v);
        })->when(request('matricule'), function ($q, $v) {
            $q->whereLike('matricule',$v );
        })->when(request('email'), function ($q, $v) {
            $q->whereLike('email', $v);
        })->when(request('telephone'), function ($q, $v) {
            $q->whereLike('telephone',$v );
        })->when(request('filtreemail'), function ($q, $v) {
            if ($v == "0") {
                $q->where('email',null);
            } elseif ($v == "1"){
                $q->where('email','!=',null);
            }
        })->paginate(25);

        return view('customs.admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('customs.admin.users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->update($request->all());
        session()->flash('success',"Modification reussit $user->name");
        return redirect()->route('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customs/admin/users/edit.blade.php
@extends('customs.layouts.main')
@section('content')
    <div class="container grid px-6 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
            Modifier le votant
        </h2>
        <div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
            <form  method="POST" class="theme-form" action="{{ route('admin.user.update',$user->id) }}">
                @csrf()
                <div class="-mx-3 md:flex mb-3">
                    <div class="md:w-1/2 px-3 mb-3 md:mb-0 mt-6">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="nom">
                            Nom & Prenom:
                        </label>
                        {{-- <div wire:ignore> --}}
                        <input name="nomprenom" value="{{ $user->nomprenom }}" @keyup="nomUpperCase = $event.target.value.toUpperCase()"
                               :value="nomUpperCase"
                               class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                        @error('nom') border-red-600 @enderror  rounded py-3 px-4 mb-2"
                               id="nom" type="text" placeholder="Jane">
                        {{-- </div> --}}
                        @error('nom')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="prenom">
                            Matricule:
                        </label>
                        {{-- <div wire:ignore> --}}
                        <input name="matricule" value="{{ $user->matricule }}"
                               @keyup="prenomUpperCase = $event.target.value.toUpperCase()"
                               :value="prenomUpperCase"
                               class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                        @error('prenom') border-red-600 @enderror rounded py-3 px-4 mb-1"
                               id="prenom" type="text" placeholder="Doe">
                        {{-- </div> --}}
                        @error('prenom')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="md:w-1/2 px-3 mb-3 md:mb-0 mt-6">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="nom">
                            Email:
                        </label>
                        {{-- <div wire:ignore> --}}
                        <input name="email" value="{{ $user->email }}" @keyup="nomUpperCase = $event.target.value.toUpperCase()"
                               :value="nomUpperCase"
                               class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                        @error('nom') border-red-600 @enderror  rounded py-3 px-4 mb-2"
                               id="nom" type="text" placeholder="Jane">
                        {{-- </div> --}}
                        @error('nom')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="prenom">
                            Telephone:
                        </label>
                        {{-- <div wire:ignore> --}}
                        <input name="telephone" value="{{ $user->telephone }}"
                            @keyup="prenomUpperCase = $event.target.value.toUpperCase()"
                            :value="prenomUpperCase"
                            class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                        @error('prenom') border-red-600 @enderror rounded py-3 px-4 mb-1"
                            id="prenom" type="text" placeholder="Doe">
                        {{-- </div> --}}
                        @error('prenom')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="md:w-1/2 px-3 mb-3 md:mb-0 mt-6">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="nom">
                            CODE:
                        </label>
                        {{-- <div wire:ignore> --}}
                        <input name="codegene" value="{{ $user->codegene }}" @keyup="nomUpperCase = $event.target.value.toUpperCase()"
                               :value="nomUpperCase"
                               class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                        @error('codegene') border-red-600 @enderror  rounded py-3 px-4 mb-2"
                               id="nom" type="text" placeholder="Jane">
                        {{-- </div> --}}
                        @error('codegene')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <!-- You should use a button here, as the anchor is only used for the example  -->
                <button type="submit" class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5
                            text-center text-white transition-colors duration-150 bg-cyan-600 border
                            border-transparent rounded-lg active:bg-cyan-600 hover:bg-cyan-700 focus:outline-none focus:shadow-outline-purple">
                    Modifier
                </button>
            </form>
        </div>
    </div>

@endsection

resources/views/customs/admin/users/index.blade.php
@extends('customs.layouts.main')
@section('content')
    <div class="container grid px-6 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
            Recherche
        </h2>
        <div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
            <form method="GET" class="theme-form" action="{{ route('admin.user.index') }}">
                @csrf()
                <input type="hidden" name="_token" value="9jwyWeFYLfVH4TJuCzmF8c3kKq8Am0C5MzEv9zQB">
                <div class="-mx-3 md:flex mb-3">
                    <div class="md:w-1/2 px-3 mb-3 md:mb-0 mt-6">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="nom">
                            Nom &amp; Prenom:
                        </label>
                        <input value="{{ old('prenom') }}" name="nomprenom" class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                          rounded py-3 px-4 mb-2" id="nom" type="text" placeholder="Jane">

                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="prenom">
                            Matricule:
                        </label>
                        <input value="{{ old('matricule') }}" name="matricule" class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                         rounded py-3 px-4 mb-1" id="prenom" type="text" placeholder="Doe">
                    </div>

                    <div class="md:w-1/2 px-3 mb-3 md:mb-0 mt-6">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="nom">
                            Email:
                        </label>
                        <input value="{{ old('email') }}" name="email" class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                          rounded py-3 px-4 mb-2" id="nom" type="text" placeholder="Jane">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="prenom">
                            Telephone:
                        </label>
                        <input value="{{ old('telephone') }}" name="telephone" class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                        rounded py-3 px-4 mb-1" id="prenom" type="text" placeholder="Doe">
                    </div>
                </div>
                <div class="-mx-3 md:flex mb-3">
                    <div class="md:w-1/2 px-3 md:mb-0">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="paysnaissance">
                            Filtre Email:
                        </label>
                        <select name="filtreemail" class="appearance-none block w-full bg-white
                            text-grey-darker border @error('filtreemail') border-red-600 @enderror rounded py-3 px-4 mb-1">
                            <option value="">{{ __("-- Selectionner Filtre --") }}</option>
                            <option value="0">{{ __("PAS DE MAIL") }}</option>
                            <option value="1">{{ __("MAIL COMPLET") }}</option>
                        </select>
                        @error('filtreemail')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="md:w-1/2 px-3 md:mb-0">
                        <label class="block uppercase tracking-wide text-zinc-500 text-xs font-bold mb-2" for="paysnaissance">
                            Filtre Telephone:
                        </label>
                        <select name="filtretelephone" class="appearance-none block w-full bg-white
                            text-grey-darker border @error('filtretelephone') border-red-600 @enderror rounded py-3 px-4 mb-1">
                            <option value="">{{ __("-- Selectionner Filtre --") }}</option>
                            <option value="0">{{ __("NUMERO INCOMPLET") }}</option>
                            <option value="1">{{ __("NUMERO COMPLET") }}</option>
                        </select>
                        @error('filtretelephone')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <!-- You should use a button here, as the anchor is only used for the example  -->
                <button type="submit" class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5
                            text-center text-white transition-colors duration-150 bg-cyan-600 border
                            border-transparent rounded-lg active:bg-cyan-600 hover:bg-cyan-700 focus:outline-none focus:shadow-outline-purple">
                    Recherche
                </button>
            </form>
        </div>
        <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200 uppercase">
            Liste des votants
        </h2>
        <div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
            <div class="w-full overflow-x-auto">
                <table class="w-full whitespace-no-wrap">
                    <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="px-4 py-3">Nom & Prenom</th>
                        <th class="px-4 py-3">Matricule</th>
                        <th class="px-4 py-3">Email</th>
                        <th class="px-4 py-3">Telephone</th>
                        <th class="px-4 py-3">Code Generer</th>
                        <th class="px-4 py-3">Status Vote</th>
                        <th class="px-4 py-3"></th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">

                    @foreach($users as $user)
                        <tr class="text-gray-700 dark:text-gray-400">
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <!-- Avatar with inset shadow -->
                                <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                                    <img class="object-cover w-full h-full rounded-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=200&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE3Nzg0fQ" alt="" loading="lazy">
                                    <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                                </div>
                                <div>
                                    <p class="font-semibold">{{ $user->nomprenom }}</p>
                                </div>
                            </div>
                        </td>
                        <td class="px-4 py-3 text-sm">
                            <p class="font-semibold">{{ $user->matricule }}</p>
                        </td>
                        <td class="px-4 py-3 text-xs">
                            @if($user->email)
                                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                  {{ $user->email }}
                                </span>
                            @else
                                <span class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:text-white dark:bg-orange-600">
                                      {{ __('Pas de e-mail') }}
                                </span>
                            @endif
                        </td>
                        <td class="px-4 py-3 text-sm">
                            {{--@php
                            dd(strlen($user->telephone))
                            @endphp--}}
                            @if(strlen($user->telephone) == 10)
                                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                  {{ $user->telephone }}
                                </span>
                            @else
                                <span class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:text-white dark:bg-orange-600">
                                  {{ $user->telephone }}
                                </span>
                            @endif
                        </td>
                        <td class="px-4 py-3 text-sm">
                            @if(!$user->codegene)
                                <span class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:text-white dark:bg-orange-600">
                                      {{ __('Pas encore generer') }}
                                </span>
                            @else
                                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                  {{ $user->codegene }}
                                </span>
                            @endif

                        </td>
                            <td class="px-4 py-3 text-sm">
                                @if($user->status != 1 ||$user->status != 1  )
                                    <span class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:text-white dark:bg-orange-600">
                                      {{ __('Pas encore vote') }}
                                </span>
                                @else
                                    <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                                  {{ __('À vote') }}
                                </span>
                                @endif

                            </td>
                        <td>
                            <a id="dropdownButton" href="{{ route('admin.user.edit',$user->id) }}"
                                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
                                Modifier
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z" />
                                    <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
            <div class="mt-3">
                {!! $users->links() !!}
            </div>
        </div>
    </div>
@endsection