routes/web.php
<?php

use App\Http\Controllers\AdministrateurController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class,'index'])->name('home');
Route::get('/', [SessionController::class , 'obtenircode'])->name('obtenircode');
Route::post('/login', [SessionController::class , 'login'])->name('session.login');
Route::post('/generatecode', [SessionController::class , 'generatecode'])->name('session.generatecode');
Route::get('/showverifcode', [SessionController::class , 'showverifcode'])->name('session.showverifcode');
Route::post('/verifcode', [SessionController::class , 'verifcode'])->name('session.verifcode');
Route::get('/sms', [SessionController::class , 'sms'])->name('sms');

Route::get('/resultat', function () {
    $candidats = \App\Models\CandidatPresidentielle::all();
    return view('voting.resultat',compact('candidats'));
});

Route::group(['prefix'=>'admin','as'=>'admin.'], function () {
    Route::get('/',[AdministrateurController::class, 'index'])->name('index');
    Route::get('/import',[AdministrateurController::class, 'import'])->name('import');
    Route::post('/import_in',[AdministrateurController::class, 'import_in'])->name('import_in');
    Route::get('/user',[UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/edit',[UserController::class, 'edit'])->name('user.edit');
    Route::post('/user/update/{id}',[UserController::class, 'update'])->name('user.update');
    Route::get('/candidat/commissaire',[AdministrateurController::class,'resultatcommissaire'])->name('resultatcommissaire');
});

Route::group(['prefix'=>'vote','as'=>'vote.'], function () {
    Route::get('/',[VoteController::class, 'index'])->name('index');
    Route::get('/commisaire',[VoteController::class, 'commisaire'])->name('commisaire');
    Route::get('/voter/{id}',[VoteController::class, 'voter'])->name('voter');
    Route::get('/voter/commissaire/{id}',[VoteController::class, 'voterCommissaire'])->name('votecommissaire');
    Route::get('/voter/commissaire-adjoint/{id}',[VoteController::class, 'voterCommissaireAdjoint'])->name('votecommissaireadjoint');
    Route::get('/felicitaion',[VoteController::class, 'felicitaion'])->name('felicitaion');
    Route::get('/votrechoix',[VoteController::class, 'votrechoix'])->name('votrechoix');
    Route::post('/fullcommissaire',[VoteController::class, 'fullCommissaire'])->name('fullcommissaire');
});

resources/views/admin/import.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Page Sidebar Ends-->
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <h3>Base inputs</h3>
                    </div>
                    <div class="col-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">                                       <i data-feather="home"></i></a></li>
                            <li class="breadcrumb-item">Form Controls</li>
                            <li class="breadcrumb-item active">Base inputs</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h5>Basic form control</h5>
                        </div>
                        <form class="form theme-form" action="{{ route('admin.import_in') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <input type="file" name="file" class="form-control">
                            <br>
                            <button class="bg-blue-100">Import User</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- Container-fluid Ends-->
@stop

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="{{ asset('assets_admin/images/favicon.png') }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ asset('assets_admin/images/favicon.png') }}" type="image/x-icon">
    <title>Ma AEJ Vote en ligne</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset("assets_admin/css/font-awesome.css") }}">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/icofont.css') }}">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/themify.css') }}">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/flag-icon.css') }}">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/feather-icon.css') }}">
    <!-- Plugins css start-->
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/bootstrap.css') }}">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/style.css') }}">
    <link id="color" rel="stylesheet" href="{{ asset('assets_admin/css/color-1.css') }}" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/responsive.css') }}">
</head>
<body>
<!-- login page start-->
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-5"><img class="bg-img-cover bg-center" src="assets_admin/images/login/3.jpg" alt="looginpage"></div>
        <div class="col-xl-7 p-0">
            <div class="login-card">
                <div>
                    <div><a class="logo text-start" href="index.html"><img class="img-fluid for-light" src="{{ asset('assets/images/maaej.jpeg') }}" alt="looginpage">
                            <img class="img-fluid for-dark" src="{{ asset('assets/images/maaej.jpeg') }}" alt="looginpage"></a></div>
                    <div class="login-main">
                        <form class="theme-form">
                            <h4>Se connecter au compte</h4>
                            <p>Entrez votre adresse électronique et votre mot de passe pour vous connecter</p>
                            <div class="form-group">
                                <label class="col-form-label">Email</label>
                                <input class="form-control" type="email" required="" placeholder="Test@gmail.com">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Mot de Passe</label>
                                <div class="form-input position-relative">
                                    <input class="form-control" type="password" name="password" required="" placeholder="*********">
                                    <div class="show-hide">
                                        <span class="show"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-0">
                                <button class="btn btn-primary btn-block w-100" type="submit">Sign in</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- latest jquery-->
    <script src="assets_admin/js/jquery-3.5.1.min.js"></script>
    <!-- Bootstrap js-->
    <script src="assets_admin/js/bootstrap/bootstrap.bundle.min.js"></script>
    <!-- feather icon js-->
    <script src="assets_admin/js/icons/feather-icon/feather.min.js"></script>
    <script src="assets_admin/js/icons/feather-icon/feather-icon.js"></script>
    <!-- scrollbar js-->
    <!-- Sidebar jquery-->
    <script src="assets_admin/js/config.js"></script>
    <!-- Plugins JS start-->
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="assets_admin/js/script.js"></script>
    <!-- login js-->
    <!-- Plugin used-->
</div>
</body>
</html>