routes/web.php
<?php

use App\Http\Controllers\AdministrateurController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class,'index'])->name('home');
Route::get('/', [SessionController::class , 'obtenircode'])->name('obtenircode');
Route::post('/login', [SessionController::class , 'login'])->name('session.login');
Route::post('/generatecode', [SessionController::class , 'generatecode'])->name('session.generatecode');
Route::get('/showverifcode', [SessionController::class , 'showverifcode'])->name('session.showverifcode');
Route::post('/verifcode', [SessionController::class , 'verifcode'])->name('session.verifcode');
Route::get('/sms', [SessionController::class , 'sms'])->name('sms');

Route::get('/resultat', function () {
    $candidats = \App\Models\CandidatPresidentielle::all();
    return view('voting.resultat',compact('candidats'));
});

Route::group(['prefix'=>'admin','as'=>'admin.'], function () {
    Route::get('/',[AdministrateurController::class, 'index'])->name('index');
    Route::get('/import',[AdministrateurController::class, 'import'])->name('import');
    Route::post('/import_in',[AdministrateurController::class, 'import_in'])->name('import_in');
    Route::get('/user',[UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/edit',[UserController::class, 'edit'])->name('user.edit');
    Route::post('/user/update/{id}',[UserController::class, 'update'])->name('user.update');
    Route::get('/candidat/commissaire',[AdministrateurController::class,'resultatcommissaire'])->name('resultatcommissaire');
});

Route::group(['prefix'=>'vote','as'=>'vote.'], function () {
    Route::get('/',[VoteController::class, 'index'])->name('index');
    Route::get('/commisaire',[VoteController::class, 'commisaire'])->name('commisaire');
    Route::get('/voter/{id}',[VoteController::class, 'voter'])->name('voter');
    Route::get('/voter/commissaire/{id}',[VoteController::class, 'voterCommissaire'])->name('votecommissaire');
    Route::get('/voter/commissaire-adjoint/{id}',[VoteController::class, 'voterCommissaireAdjoint'])->name('votecommissaireadjoint');
    Route::get('/felicitaion',[VoteController::class, 'felicitaion'])->name('felicitaion');
    Route::get('/votrechoix',[VoteController::class, 'votrechoix'])->name('votrechoix');
    Route::post('/fullcommissaire',[VoteController::class, 'fullCommissaire'])->name('fullcommissaire');
});

resources/views/voting/choix_vote.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <h3>VOTER POUR</h3>
                    </div>
                    <div class="col-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">
                                    <i data-feather="home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">Users</li>
                            <li class="breadcrumb-item active">User Cards</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-12 alert-sec">
                    <div class="card bg-img">
                        <div class="card-header">
                            <div class="header-top">
                                <h5 class="m-0">Passer au vote !!!  </h5>
                                <div class="dot-right-icon"><i class="fa fa-ellipsis-h"></i></div>
                            </div>
                        </div>
                        <div class="card-body">
                            <a type="buttom" href="{{ route('vote.index') }}" class="btn btn-lg btn-info">
                                VOTER POUR LA PRESIDENCE
                            </a>
                           {{-- <a type="buttom" href="{{ route('vote.commisaire') }}" class="btn btn-lg btn-info">
                                VOTER POUR LES COMMISSAIRES AU COMPTE
                            </a>--}}
                            {{--<div class="body-bottom">
                                <h6>Felicitation !!!</h6><span class="font-roboto"> Votre vote a ete pris en compte... </span>
                            </div>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/voting/comissaire.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <h3>Candidat au commissariat au compte</h3>
                    </div>
                    <div class="col-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">
                                    <i data-feather="home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">Users</li>
                            <li class="breadcrumb-item active">User Cards</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.inc.flash')
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                @foreach($commissaires as $commissaire)
                <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                    <div class="card custom-card p-0">
                        <div class="card-header"><img class="img-fluid" src="{{ asset('images/commissaire/'.$commissaire->image) }}" alt=""></div>
                        <div class="card-profile"><img class="rounded-circle" src="{{ asset('images/commissaire/'.$commissaire->image) }}" alt=""></div>
                        <div class="text-center profile-details">
                            <h5>{{$commissaire->nom_prenom}}</h5>
                            <h6>Candidat</h6>

                            <a type="buttom" href="{{ route('vote.votecommissaire',['id' => $commissaire->id ]) }}" class="btn btn-lg btn-secondary">
                                Cliquez ici pour me voter
                            </a>
                        <br>
                        </div>
                        <div class="card-footer row">
                            <div class="col-10 col-sm-4">
                                {{--<h6>Vote</h6>
                                <h5 class="counter">{{ $commissaire->vote }}</h5>--}}
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div></div>
        <!-- Container-fluid Ends-->
    @stop

resources/views/voting/felicitation.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <h3>Felicitation !!! , Votre vote a ete pris en compte...</h3>
                    </div>
                    {{--<div class="col-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">
                                    <i data-feather="home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">Users</li>
                            <li class="breadcrumb-item active">User Cards</li>
                        </ol>
                    </div>--}}
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        @include('layouts.inc.flash')
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-12 alert-sec">
                    <div class="card bg-img">
                        <div class="card-header">
                            <div class="header-top">
                                <h5 class="m-0" style="color: red;">Felicitation !!!  </h5>
                                <div class="dot-right-icon"><i class="fa fa-ellipsis-h"></i></div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="body-bottom" style="color: green;">
                                <h6>Felicitation !!!</h6><span class="font-roboto"> Votre vote a ete pris en compte... </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/voting/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="{{ asset('assets_admin/images/favicon.png') }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ asset('assets_admin/images/favicon.png') }}" type="image/x-icon">
    <title>Ma AEJ Vote en ligne</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset("assets_admin/css/font-awesome.css") }}">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/icofont.css') }}">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/themify.css') }}">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/flag-icon.css') }}">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/feather-icon.css') }}">
    <!-- Plugins css start-->
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/bootstrap.css') }}">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/style.css') }}">
    <link id="color" rel="stylesheet" href="{{ asset('assets_admin/css/color-1.css') }}" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/responsive.css') }}">
</head>
<body>
<!-- login page start-->
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-5"><img class="bg-img-cover bg-center" src="{{ asset('assets/images/maaej.jpeg') }}" alt="looginpage"></div>
        <div class="col-xl-7 p-0">
            <div class="login-card">
                <div>
                    <div><a class="logo text-start" href="index.html">
                            <img class="for-light" src="{{ asset('assets/images/maaej.jpeg') }}" height="100" alt="looginpage">
                            <img class="for-dark" src="{{ asset('assets/images/maaej.jpeg') }}" height="100" alt="looginpage"></a></div>
                    <div class="login-main">
                        <form  method="POST" class="theme-form" action="{{ route('session.generatecode') }}">
                            @csrf()
                            <h4>Obtenez un code ici.</h4>
                            <p>Entrez votre email et votre telephone pour obtenir</p>
                            @include('layouts.inc.flash')
                            <div class="form-group">
                                <label class="col-form-label">Email</label>
                                <input class="form-control" type="email" name="email" required="" placeholder="Test@gmail.com">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Telephone</label>
                                <div class="form-input position-relative">
                                    <input class="form-control" type="text" name="telephone" required="" placeholder="0101010101">
                                    {{--<div class="show-hide">
                                        <span class="show"></span>
                                    </div>--}}
                                </div>
                            </div>
                            <div class="form-group mb-0">
                                <button class="btn btn-primary btn-block w-100" type="submit">Verifier & Obtenir un code ici</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- latest jquery-->
    <script src="{{ asset('assets_admin/js/jquery-3.5.1.min.js') }}"></script>
    <!-- Bootstrap js-->
    <script src="{{ asset('assets_admin/js/bootstrap/bootstrap.bundle.min.js') }}"></script>
    <!-- feather icon js-->
    <script src="{{ asset('assets_admin/js/icons/feather-icon/feather.min.js') }}"></script>
    <script src="{{ asset('assets_admin/js/icons/feather-icon/feather-icon.js') }}"></script>
    <!-- scrollbar js-->
    <!-- Sidebar jquery-->
    <script src="{{ asset('assets_admin/js/config.js') }}"></script>
    <!-- Plugins JS start-->
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="{{ asset('assets_admin/js/script.js') }}"></script>
    <!-- login js-->
    <!-- Plugin used-->
</div>
</body>
</html>

resources/views/voting/president.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <h3>Candidat à la présidence</h3>
                    </div>
                    <div class="col-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">
                                    <i data-feather="home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">Users</li>
                            <li class="breadcrumb-item active">User Cards</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.inc.flash')
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                @foreach($candidats as $candidat)
                <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                    <div class="card custom-card p-0">
                        <div class="card-header"><img src="{{ asset('images/president/'.$candidat->image) }}" alt=""></div>
                        <div class="card-profile"><img class="rounded-circle" src="{{ asset('images/president/'.$candidat->image) }}" alt=""></div>
                        <div class="text-center profile-details">
                            <h5>{{$candidat->nom_prenom}}</h5>
                            <h6>Candidat</h6>

                            <a type="buttom" href="{{ route('vote.voter',['id' => $candidat->id ]) }}" class="btn btn-lg btn-secondary">
                                Cliquez ici pour me voter
                            </a>
                        <br>
                        </div>
                        <div class="card-footer row">
                            <div class="col-10 col-sm-4">
                                {{--<h6>Vote</h6>
                                <h5 class="counter">{{ $candidat->vote }}</h5>--}}
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div></div>
        <!-- Container-fluid Ends-->
    @stop

resources/views/voting/resultat.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <h3>Vote provisoire</h3>
                        <h3>Nombre Total: {{ \App\Models\UserCandidatPresidentielle::count() }}</h3>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.inc.flash')
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                @foreach($candidats as $candidat)
                <div class="col-md-6 col-lg-6 col-xl-4 box-col-6">
                    <div class="card custom-card p-0">
                        <div class="card-header"><img src="{{ asset('images/president/'.$candidat->image) }}" alt=""></div>
                        <div class="card-profile"><img class="rounded-circle" src="{{ asset('images/president/'.$candidat->image) }}" alt=""></div>
                        <div class="text-center profile-details">
                            <h5>{{$candidat->nom_prenom}}</h5>
                            <h6>Candidat</h6>
                        <br>`
                        </div>`
                        <div class="card-footer row">
                            <div class="col-10 col-sm-4">
                                <h6>Vote</h6>
                                <h5 class="counter">{{ $candidat->vote }}</h5>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div></div>
        <!-- Container-fluid Ends-->
    @stop
@section('js')
    <script>
        var time = new Date().getTime();
        $(document.body).bind("mousemove keypress", function(e) {
            time = new Date().getTime();
        });

        function refresh() {
            if(new Date().getTime() - time >= 60000)
                window.location.reload(true);
            else
                setTimeout(refresh, 10000);
        }

        setTimeout(refresh, 10000);
    </script>
@endsection

resources/views/voting/verifcode.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="{{ asset('assets_admin/images/favicon.png') }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ asset('assets_admin/images/favicon.png') }}" type="image/x-icon">
    <title>Ma AEJ Vote en ligne</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset("assets_admin/css/font-awesome.css") }}">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/icofont.css') }}">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/themify.css') }}">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/flag-icon.css') }}">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/feather-icon.css') }}">
    <!-- Plugins css start-->
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/vendors/bootstrap.css') }}">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/style.css') }}">
    <link id="color" rel="stylesheet" href="{{ asset('assets_admin/css/color-1.css') }}" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets_admin/css/responsive.css') }}">
</head>
<body>
<!-- login page start-->
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-5"><img class="bg-img-cover bg-center" src="{{ asset('assets/images/maaej.jpeg') }}" alt="looginpage"></div>
        <div class="col-xl-7 p-0">
            <div class="login-card">
                <div>
                    <div><a class="logo text-start" href="index.html">
                            <img class="for-light" src="{{ asset('assets/images/maaej.jpeg') }}" height="100" alt="looginpage">
                            <img class="for-dark" src="{{ asset('assets/images/maaej.jpeg') }}" height="100" alt="looginpage"></a></div>
                    <div class="login-main">

                        <form  method="POST" class="theme-form" action="{{ route('session.verifcode') }}">
                            @csrf()
                            <h4>Verifier code ici</h4>
                            <p>Renseignez le code recu par mail ici</p>
                            @include('layouts.inc.flash')
                            @include('layouts.inc.message')
                            <div class="form-group">
                                <label class="col-form-label">Code Generer</label>
                                <input class="form-control" type="text" name="codegene" required="" placeholder="Code Generer">
                            </div>
                            <div class="form-group mb-0">
                                <button class="btn btn-primary btn-block w-100" type="submit">Verifier</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- latest jquery-->
    <script src="{{ asset('assets_admin/js/jquery-3.5.1.min.js') }}"></script>
    <!-- Bootstrap js-->
    <script src="{{ asset('assets_admin/js/bootstrap/bootstrap.bundle.min.js') }}"></script>
    <!-- feather icon js-->
    <script src="{{ asset('assets_admin/js/icons/feather-icon/feather.min.js') }}"></script>
    <script src="{{ asset('assets_admin/js/icons/feather-icon/feather-icon.js') }}"></script>
    <!-- scrollbar js-->
    <!-- Sidebar jquery-->
    <script src="{{ asset('assets_admin/js/config.js') }}"></script>
    <!-- Plugins JS start-->
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="{{ asset('assets_admin/js/script.js') }}"></script>
    <!-- login js-->
    <!-- Plugin used-->
</div>
</body>
</html>