routes/web.php
<?php

use App\Http\Controllers\AdministrateurController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class,'index'])->name('home');
Route::get('/', [SessionController::class , 'obtenircode'])->name('obtenircode');
Route::post('/login', [SessionController::class , 'login'])->name('session.login');
Route::post('/generatecode', [SessionController::class , 'generatecode'])->name('session.generatecode');
Route::get('/showverifcode', [SessionController::class , 'showverifcode'])->name('session.showverifcode');
Route::post('/verifcode', [SessionController::class , 'verifcode'])->name('session.verifcode');
Route::get('/sms', [SessionController::class , 'sms'])->name('sms');

Route::get('/resultat', function () {
    $candidats = \App\Models\CandidatPresidentielle::all();
    return view('voting.resultat',compact('candidats'));
});

Route::group(['prefix'=>'admin','as'=>'admin.'], function () {
    Route::get('/',[AdministrateurController::class, 'index'])->name('index');
    Route::get('/import',[AdministrateurController::class, 'import'])->name('import');
    Route::post('/import_in',[AdministrateurController::class, 'import_in'])->name('import_in');
    Route::get('/user',[UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/edit',[UserController::class, 'edit'])->name('user.edit');
    Route::post('/user/update/{id}',[UserController::class, 'update'])->name('user.update');
    Route::get('/candidat/commissaire',[AdministrateurController::class,'resultatcommissaire'])->name('resultatcommissaire');
});

Route::group(['prefix'=>'vote','as'=>'vote.'], function () {
    Route::get('/',[VoteController::class, 'index'])->name('index');
    Route::get('/commisaire',[VoteController::class, 'commisaire'])->name('commisaire');
    Route::get('/voter/{id}',[VoteController::class, 'voter'])->name('voter');
    Route::get('/voter/commissaire/{id}',[VoteController::class, 'voterCommissaire'])->name('votecommissaire');
    Route::get('/voter/commissaire-adjoint/{id}',[VoteController::class, 'voterCommissaireAdjoint'])->name('votecommissaireadjoint');
    Route::get('/felicitaion',[VoteController::class, 'felicitaion'])->name('felicitaion');
    Route::get('/votrechoix',[VoteController::class, 'votrechoix'])->name('votrechoix');
    Route::post('/fullcommissaire',[VoteController::class, 'fullCommissaire'])->name('fullcommissaire');
});

app/Http/Controllers/VoteController.php
<?php

namespace App\Http\Controllers;

use App\Models\CandidatComissaireCompte;
use App\Models\CandidatPresidentielle;
use App\Models\User;
use App\Models\UserCandidatComissaireCompte;
use App\Models\UserCandidatPresidentielle;
use Illuminate\Http\Request;

class VoteController extends Controller
{
    public function index(){

        $user = session()->get('user_data');
        $code = session()->get('code');

        if (!$user && !$code) {
            return view('customs.vote.index');
        }

        $candidats = CandidatPresidentielle::all();
        return view('customs.vote.comissaire-adjoint',compact('candidats'));
    }

    public function commisaire(){
        $user = session()->get('user_data');
        $code = session()->get('code');
        if (!$user && !$code) {
            return view('customs.vote.index');
        }
        $commissaires = CandidatComissaireCompte::all();
        $candidats = CandidatPresidentielle::all();
        //return view('voting.comissaire',compact('commissaires'));
        return view('customs.vote.comissaire',compact('commissaires','candidats'));
    }

    public function voter ($id) {
        $code = session()->get('code');
        //dd($code);
        $user = User::where('codegene',$code)->where('status',0)->first();

        if(!$user){
            session()->flash('warning',"Vous n'êtes pas autorisé a vote.");
            return back();
        } else {
            $user->status = true;
            $user->save();

            $votecondidat = new UserCandidatPresidentielle();
            $votecondidat->userId = $user->id;
            $votecondidat->email = $user->email;
            $votecondidat->telephone = $user->telephone;
            $votecondidat->candidatpresidentiellesId = $id;
            $votecondidat->save();

            if($votecondidat){
                $candidat = CandidatPresidentielle::find($id);
                $candidat->vote = $candidat->vote + 1;
                $candidat->save();
            }
            session()->flash('success',"Felicitation !!!,Votre vote a ete pris en compte...");
            return redirect()->route('vote.felicitaion');
        }
    }

    public function voterCommissaireAdjoint($id){

        $code = session()->get('code');
        $user = User::where('codegene',$code)->where('status',0)->first();

        if(!$user){
            session()->flash('warning',"Vous n'êtes pas autorisé, vous avez déjà voté.");
            return view('customs.vote.index');
        } else {
            $user->status = true;
            $user->save();

            $votecondidat = new UserCandidatPresidentielle();
            $votecondidat->userId = $user->id;
            $votecondidat->email = $user->email;
            $votecondidat->telephone = $user->telephone;
            $votecondidat->candidatpresidentiellesId = $id;
            $votecondidat->save();

            if($votecondidat){
                $candidat = CandidatPresidentielle::find($id);
                session()->put('nom_comadjoint',$candidat->nom_prenom);
                $candidat->vote = $candidat->vote + 1;
                $candidat->save();
            }

            session()->flash('success',"Felicitation !!!,Votre vote a ete pris en compte...");
            return redirect()->route('vote.felicitaion');
        }
    }

    public function fullCommissaire(Request $request){

        /*"vote_commissaire" => "1"
        "vote_commissaire_adjoint" => "1"*/

        if($request->vote_commissaire || $request->vote_commissaire_adjoint){
            $code = session()->get('code');
            $user_data = session()->get('user_data');
            $user = User::where('codegene',$code)->where('status_com',0)->where('status',0)->first();

            if(!$user){
                session()->flash('warning',"Vous n'êtes pas autorisé, vous avez déjà voté.");
                return view('customs.vote.index');
            } else if ($code && $user_data) {

                if ($request->vote_commissaire) {

                    $user->status_com = true;
                    $votecondidat = new UserCandidatComissaireCompte();
                    $votecondidat->userId = $user->id;
                    $votecondidat->email = $user->email;
                    $votecondidat->telephone = $user->telephone;
                    $votecondidat->candidatcomissaireId = $request->vote_commissaire;
                    $votecondidat->save();

                    if($votecondidat){
                        $candidat = CandidatComissaireCompte::find($request->vote_commissaire);
                        session()->put('nom_commissaire',$candidat->nom_prenom);
                        $candidat->vote = $candidat->vote + 1;
                        $candidat->save();
                    }

                } else{
                    $user->status_com = true;
                    $votecondidat = new UserCandidatComissaireCompte();
                    $votecondidat->userId = $user->id;
                    $votecondidat->email = $user->email;
                    $votecondidat->telephone = $user->telephone;
                    $votecondidat->candidatcomissaireId = 0;
                    $votecondidat->save();
                }

                if ($request->vote_commissaire_adjoint) {

                    $user->status = true;
                    $votecondidat_adj = new UserCandidatPresidentielle();
                    $votecondidat_adj->userId = $user->id;
                    $votecondidat_adj->email = $user->email;
                    $votecondidat_adj->telephone = $user->telephone;
                    $votecondidat_adj->candidatpresidentiellesId = $request->vote_commissaire_adjoint;
                    $votecondidat_adj->save();

                    if($votecondidat_adj){
                        $candidat = CandidatPresidentielle::find($request->vote_commissaire_adjoint);
                        session()->put('nom_commissaire_adjoint',$candidat->nom_prenom);
                        $candidat->vote = $candidat->vote + 1;
                        $candidat->save();
                    }

                }else {
                    $user->status = true;
                    $votecondidat_adj = new UserCandidatPresidentielle();
                    $votecondidat_adj->userId = $user->id;
                    $votecondidat_adj->email = $user->email;
                    $votecondidat_adj->telephone = $user->telephone;
                    $votecondidat_adj->candidatpresidentiellesId = 0;
                    $votecondidat_adj->save();
                }
                // mise a jour des status du votant
                $user->save();
                session()->flash('success',"Felicitation !!!,Votre vote a ete pris en compte...");
                return redirect()->route('vote.felicitaion');
            }
        } else {
            session()->flash('warning',"Vous devez faire au moins un choix !!!");
            return redirect()->route('vote.commisaire');
        }
    }

    public function voterCommissaire ($id) {

        $code = session()->get('code');
        $user_data = session()->get('user_data');

        $user = User::where('codegene',$code)->where('status_com',0)->first();

        if(!$user){
            session()->flash('warning',"Vous n'êtes pas autorisé, vous avez déjà voté.");
            return view('customs.vote.index');
        } else if ($code && $user_data)  {
            $user->status_com = true;
            $user->save();

            $votecondidat = new UserCandidatComissaireCompte();
            $votecondidat->userId = $user->id;
            $votecondidat->email = $user->email;
            $votecondidat->telephone = $user->telephone;
            $votecondidat->candidatcomissaireId = $id;
            $votecondidat->save();

            if($votecondidat){
                $candidat = CandidatComissaireCompte::find($id);
                session()->put('nom_com',$candidat->nom_prenom);
                $candidat->vote = $candidat->vote + 1;
                $candidat->save();
            }

            session()->flash('success',"Felicitation !!!,Votre vote a ete pris en compte...");
            return redirect()->route('vote.felicitaion');
            //return redirect()->route('customs.vote.felicitaion');
        }
    }

    public function felicitaion(){

        $code = session()->get('code');

        if (!$code) {
            session()->flash('warning',"Cet accès n'est pas autorisé.");
            return view('customs.vote.index');
        }

        $user = User::where('codegene',$code)->where('status',1)->where('status_com',1)->first();

        if($user){
            $nom_commissaire = session()->get('nom_commissaire');
            $nom_commissaire_adjoint = session()->get('nom_commissaire_adjoint');
            session()->flash('success',"Felicitation !!!, vous avez bien vote le commissaire au compte $nom_commissaire le commissaire au compte adjoint $nom_commissaire_adjoint...");
            return view('customs.vote.felicitaion');
        }

        $user_cadjoint = User::where('codegene',$code)->where('status',1)->first();

        if($user_cadjoint){
            $nom_commissaire_adjoint = session()->get('nom_commissaire_adjoint');
            session()->flash('success',"Felicitation !!!,Vous avez bien vote le commissaire au compte adjoint $nom_commissaire_adjoint...");
        }

        $user_com = User::where('codegene',$code)->where('status_com',1)->first();

        if($user_com){
            $nom_commissaire = session()->get('nom_commissaire');
            session()->flash('success',"Felicitation !!!,Vous avez bien vote le commissaire au compte $nom_commissaire...");
        }

        return view('customs.vote.felicitaion');
    }

    public function votrechoix(){

        $code = session()->get('code');
        if (!$code) {
            session()->flash('warning',"Cet accès n'est pas autorisé. Veuillez remplir les informations c-dessous !!!");

resources/views/customs/vote/choix_vote.blade.php
@extends('customs.admin.layouts.main')
@section('content')
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="flex-1 h-full max-w-4xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800">
            <div class="flex flex-col overflow-y-auto md:flex-row">
               <div class="h-32 md:h-auto md:w-1/2">
                    <img
                        aria-hidden="true"
                        class="object-cover w-full h-full dark:hidden"
                        src="{{ asset('assets/images/maaej.jpeg') }}"
                        alt="Office"
                    />
                    <img
                        aria-hidden="true"
                        class="hidden object-cover w-full h-full dark:block"
                        src="{{ asset('assets/images/maaej.jpeg') }}"
                        alt="Office"
                    />
                </div>

                <div class="flex items-center justify-center p-2 sm:p-12 md:w-full">
                    <div class="w-full">
                        <div class="px-6 my-6">
                            <a href="{{ route('vote.commisaire') }}"
                               class="flex items-center text-center
                               h-12
                               justify-between px-3 py-3
                               text-sm font-medium leading-5 text-white
                               transition-colors duration-150 bg-sky-600 border
                               border-transparent rounded-lg active:bg-purple-600
                               hover:bg-sky-700 focus:outline-none
                               focus:shadow-outline-purple">
                                VOTER POUR LES COMMISSAIRES AU COMPTE
                            </a>
                        </div>
                    </div>
               </div>
                {{--<div class="flex items-center justify-center p-2 sm:p-12 md:w-full">
                    <div class="w-full">
                        <div class="px-6 my-6">
                            <a href="{{ route('vote.index') }}"
                               class="flex items-center text-center
                               h-12
                               justify-between px-3 py-3
                               text-sm font-medium leading-5 text-white
                               transition-colors duration-150 bg-sky-600 border
                               border-transparent rounded-lg active:bg-purple-600
                               hover:bg-sky-700 focus:outline-none
                               focus:shadow-outline-purple">
                                VOTER POUR LES ADJOINTS COMMISSAIRES AU COMPTE
                            </a>
                        </div>
                    </div>
                </div>--}}

            </div>
        </div>
    </div>
@endsection

resources/views/customs/vote/comissaire-adjoint.blade.php
@extends('customs.admin.layouts.main')
@section('content')
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="flex-1 h-full max-w-5xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800">
            <h2 class="my-6 text-2xl text-center font-semibold text-green-700 dark:text-green-200 bg-green-100">
                LES CANDIDATS AU COMMISSARIAT-ADJOINT AU COMPTE
            </h2>
            <div class="flex flex-col overflow-y-auto md:flex-row">
                @foreach($candidats as $candidat)
                    <div class="flex items-center justify-center sm:p-12 md:w-1/2">
                        <div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
                            <img src="{{ asset('images/commissaire/'.$candidat->image) }}" class="w-full">
                            <div class="text-center">
                                {{--<h1 class="text-1xl">{{$commissaire->nom_prenom}}</h1>--}}
                                <h2 class="my-6 text-base overflow-x-auto font-semibold text-gray-700 dark:text-gray-200">
                                    {{$candidat->nom_prenom}}
                                </h2>
                                <p class="font-sans font-light text-grey-100 mb-6">
                                    <a type="buttom" href="{{ route('vote.votecommissaire',['id' => $candidat->id ]) }}"
                                       class="text-center
                                               h-12 py-3 px-3
                                               text-sm font-medium leading-5 text-white
                                               transition-colors duration-150 bg-orange-600 border
                                               border-transparent rounded-lg active:bg-orange-600
                                               hover:bg-orange-700 focus:outline-none
                                               uppercase
                                               focus:shadow-outline-purple">
                                        Cliquez ici pour me voter
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/customs/vote/comissaire.blade.php
@extends('customs.admin.layouts.main')
@section('content')
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="flex-1 h-full max-w-3xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800">
            <form action="{{ route('vote.fullcommissaire') }}" method="POST">
                @csrf()
                <h2 class="my-6 text-2xl text-center font-semibold text-green-700 dark:text-green-200 bg-green-100">
                    LES CANDIDATS AU COMMISSARIAT AUX COMPTES
                </h2>
                <div class="flex flex-col md:px-40 overflow-y-auto md:flex-row">
                    @foreach($commissaires as $commissaire)
                        <div class="flex text-center justify-center sm:p-12">
                            <div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
                                <img src="{{ asset('images/commissaire/'.$commissaire->image) }}" class="w-full">
                                <div class="text-center">
                                    {{--<h1 class="text-1xl">{{$commissaire->nom_prenom}}</h1>--}}
                                    <h2 class="my-6 text-base overflow-x-auto font-semibold text-gray-700 dark:text-gray-200">
                                        {{$commissaire->nom_prenom}}
                                    </h2>
                                    <div class="flex items-center mb-6 ml-3">
                                        <div class="flex items-center h-5">
                                            <input id="vote_commissaire"  name="vote_commissaire" value="{{ $commissaire->id }}"
                                                   aria-describedby="vote_commissaire" type="checkbox" class="w-4 h-4 bg-gray-50 rounded border border-gray-300
                                                   focus:ring-3 focus:ring-blue-300 dark:bg-gray-700
                                                   dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800">
                                        </div>
                                        <div class="ml-3 text-sm">
                                            <label for="remember" class="uppercase text-cyan-500 font-medium dark:text-gray-300">
                                                Cochez ici pour que le candidat Ouattara Ouolo Souleymane soit élu Commissaire aux Comptes.
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>

                <h2 class="my-6 text-2xl text-center font-semibold text-green-700 dark:text-green-200 bg-green-100">
                    LES CANDIDATS AU COMMISSARIAT-ADJOINT AUX COMPTES
                </h2>
                <div class="flex flex-col md:px-40 overflow-y-auto md:flex-row">
                    @foreach($candidats as $candidat)
                        <div class="flex text-center justify-center sm:p-12">
                            <div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
                                <img src="{{ asset('images/commissaire/'.$candidat->image) }}" class="w-full">
                                <div class="text-center">
                                    {{--<h1 class="text-1xl">{{$commissaire->nom_prenom}}</h1>--}}
                                    <h2 class="my-6 text-base overflow-x-auto font-semibold text-gray-700 dark:text-gray-200">
                                        {{$candidat->nom_prenom}}
                                    </h2>
                                    <div class="flex items-center mb-6 ml-3">
                                        <div class="flex items-center h-5">
                                            <input id="vote_commissaire_adjoint" value="{{ $candidat->id }}"  name="vote_commissaire_adjoint"
                                                   aria-describedby="vote_commissaire_adjoint" type="checkbox"
                                                   class="w-4 h-4 bg-gray-50 rounded border border-gray-300
                                                   focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600
                                                   dark:focus:ring-blue-600 dark:ring-offset-gray-800">
                                        </div>
                                        <div class="ml-3 text-sm">
                                            <label for="remember" class="uppercase font-medium text-cyan-500 dark:text-gray-300">
                                                Cochez ici pour que le candidat Bamba Inza soit élu commissaire aux Comptes Adjoint.
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>

                <hr class="my-8" />

                <div class="flex items-center mb-6 px-10 md:px-40">
                    <button type="submit"
                       class="text-center h-12 py-3 px-3 w-25
                          text-sm font-medium leading-5 text-white
                          transition-colors duration-150 bg-orange-600 border
                           border-transparent rounded-lg active:bg-orange-600
                           hover:bg-orange-700 focus:outline-none
                           uppercase focus:shadow-outline-purple">
                        Cliquez ici pour me voter
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/customs/vote/dejavote.blade.php
@extends('customs.admin.layouts.main')
@section('content')
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="flex-1 h-full max-w-5xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800">
            <div class="flex flex-col overflow-y-auto md:flex-row">
                    @forelse(['danger', 'warning', 'success', 'info'] as $msg)
                        @if (Session::has($msg) )
                            <div class="flex items-center justify-center sm:p-12 md:w-2/2">
                                <h2 class="my-6 text-2xl text-center font-semibold text-red-700 dark:text-red-200 bg-red-400">
                                    {{ Session::get($msg) }}
                                </h2>
                            </div>
                        @endif
                    @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/customs/vote/felicitaion.blade.php
@extends('customs.admin.layouts.main')
@section('content')
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="flex-1 h-full max-w-5xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800">
            <div class="flex flex-col overflow-y-auto md:flex-row">
                @forelse(['danger', 'warning', 'success', 'info'] as $msg)
                    @if (Session::has($msg) )
                        <div class="flex text-center justify-center sm:p-12 md:w-full">
                            <h2 class="my-6 text-2xl py-3 px-3 text-center rounded font-semibold text-green-700 dark:text-green-200 bg-green-100">
                                {{ Session::get($msg) }}
                            </h2>
                        </div>
                    @endif
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/customs/vote/index.blade.php
@extends('customs.admin.layouts.main')
@section('content')
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div
            class="flex-1 h-full max-w-4xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800"
        >
            <div class="flex flex-col overflow-y-auto md:flex-row">
                <div class="h-32 md:h-auto md:w-1/2">
                    <img
                        aria-hidden="true"
                        class="object-cover w-full h-full dark:hidden"
                        src="{{ asset('assets/images/maaej.jpeg') }}"
                        alt="Office"
                    />
                    <img
                        aria-hidden="true"
                        class="hidden object-cover w-full h-full dark:block"
                        src="{{ asset('assets/images/maaej.jpeg') }}"
                        alt="Office"
                    />
                </div>

                    <div class="flex items-center justify-center p-6 sm:p-12 md:w-1/2">
                    <div class="w-full">
                        <h1 class="mb-4 text-2xl text-center font-semibold text-gray-700 dark:text-gray-200">
                            Obtenez un code ici.
                        </h1>
                        <p class="text-xl text-center text-orange-500">Entrez votre email et votre telephone pour obtenir</p>
                        <hr class="my-8" />
                        @include('layouts.inc.flash')
                        <form  method="POST" class="theme-form" action="{{ route('session.generatecode') }}">
                            @csrf()
                            <label class="block text-sm">
                                <span class="text-gray-700 dark:text-gray-400">Email</span>
                                <input required="" name="email"
                                    class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                    @error('email') border-red-600 @enderror  rounded py-3 px-4 mb-2"
                                    placeholder="Jane Doe"
                                />
                            </label>
                            <label class="block mt-4 text-sm">
                                <span class="text-gray-700 dark:text-gray-400">Telephone</span>
                                <input name="telephone"
                                    class="appearance-none block w-full bg-grey-lighter text-grey-darker border
                                    @error('telephone') border-red-600 @enderror  rounded py-3 px-4 mb-2"
                                    placeholder="0101010101"
                                    type="text"
                                />
                            </label>

                            <!-- You should use a button here, as the anchor is only used for the example  -->
                            <button type="submit" class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5
                            text-center text-white transition-colors duration-150 bg-cyan-600 border
                            border-transparent rounded-lg active:bg-cyan-600 hover:bg-cyan-700 focus:outline-none focus:shadow-outline-purple">
                                Verifier & Obtenir un code ici
                            </button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection